### ISSUE TITLE
Feature request : Option to disable potential parameters printing

### ISSUE THREAD

**Issue by naik-aakash** [bigd4/PyNEP#25]
Hi @bigd4, would it be possible to add an option to suppress the potential parameter printing when using the NEP potential with a Python interface ?

I am not very much familiar with C++, Thus am asking.

But I could narrow down it to this line here: https://github.com/bigd4/PyNEP/blob/fbbde31b928d0330c4ff795cd1fe3f473091d6b6/nep_cpu/src/nep.cpp#L2545

Setting it to false in the C++ code , I am able to suppress it in python interface as well. But I could not figure it out how can I add it as arg to the ASE NEP calculator https://github.com/bigd4/PyNEP/blob/fbbde31b928d0330c4ff795cd1fe3f473091d6b6/pynep/calculate.py#L10
 

Any hints on this would be nice, then I am happy to raise a PR for the same.

**Comment by bigd4** [comment]
I am not familiar with C++ as well. If possible, I don't want to modify the `nep.cpp` code, otherwise every update to this file would then require re-modification. Maybe redirect stdout in python can resolve this problem (or may not because it may not affect `std::cout` in C++). I will try this to see if it works.
